<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="thrymr-To-be-filled-by-O-E-M" name="Test" tests="7" failures="1" timestamp="31 Dec 2019 08:56:37 GMT" time="0.033" errors="0">
  <testcase name="setUp" time="0.008" classname="com.testng.poc.TestCase1"/>
  <testcase name="setUp" time="0.001" classname="com.testng.poc.TestCase2"/>
  <testcase name="login" time="0.001" classname="com.testng.poc.TestCase1"/>
  <testcase name="searchCustomer" time="0.001" classname="com.testng.poc.TestCase2"/>
  <testcase name="tearDown" time="0.002" classname="com.testng.poc.TestCase1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.testng.poc.TestCase1.tearDown(TestCase1.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tearDown -->
  <testcase name="addCustomer" time="0.001" classname="com.testng.poc.TestCase2"/>
  <testcase name="tearDown" time="0.0" classname="com.testng.poc.TestCase2"/>
</testsuite> <!-- Test -->
